//! Core data structures and encoder for LT fountain codes.
//!
//! A [`Droplet`] is the fundamental unit of encoded data — a payload formed by
//! XORing $d$ source blocks, where $d$ is sampled from a
//! [`DegreeDistribution`] (typicallythe [`RobustSoliton`] distribution).
//!
//! The [`Encoder`] generates droplets deterministically from [`EpochParams`],
//! enabling any peer with the same parameters to independently verify the
//! encoding graph structure without transmitting it out-of-band.
//!
//! Droplets are consumed by [`peeling_decode`](crate::decoder::peeling_decode)
//! to recover the original source blocks.
//!
//! # Examples
//!
//! ```
//! use sef::distribution::RobustSoliton;
//! use sef::droplet::{EpochParams, Encoder};
//!
//! let k = 10;
//! let blocks: Vec<Vec<u8>> = (0..k).map(|i| vec![i as u8; 64]).collect();
//! let params = EpochParams::new(0, k as u32, [0u8; 32]);
//! let rsd = RobustSoliton::new(k, 0.1, 0.5);
//!
//! let encoder = Encoder::new(&params, &rsd, &blocks);
//! let droplet = encoder.generate(0);
//! assert!(droplet.validate(k as u32).is_ok());
//! ```

use rand::{SeedableRng, seq::index::sample};
use rand_chacha::ChaCha8Rng;
use sha2::{Digest, Sha256};

use crate::{distribution::DegreeDistribution, xor};

/// A fountain-coded droplet encoding one or more source blocks via XOR.
///
/// Each droplet is generated by sampling a 'degree' $d$ from the Robust
/// Soliton Distribution and XORing $d$ source blocks together.
#[derive(Debug, Clone)]
pub struct Droplet {
    /// Epoch this droplet belongs to, linking it to a specific set of source blocks
    /// and their shared [`EpochParams`].
    pub epoch_id: u64,

    /// Unique identifier within the epoch. Together with [`EpochParams::epoch_seed`],
    /// this deterministically derives the per-droplet PRNG — making the encoding
    /// graph structure reproducible by any peer.
    pub droplet_id: u64,

    /// Sorted, unique indices of source blocks in $[0, K)$ that were XORed to
    /// form [`payload`](Droplet::payload). The length of this vector equals the
    /// sampled degree $d$.
    pub indices: Vec<u32>,

    /// Byte length of the longest source block among those selected, used as the
    /// canonical payload size. Shorter blocks are implicitly zero-padded to this
    /// length during XOR; the decoder uses it to truncate recovered blocks to
    /// their original size.
    pub padded_len: u32,

    /// The XOR-combined payload of the $d$ selected source blocks.
    pub payload: Vec<u8>,
}

/// Parameters for an epoch of blocks to be fountain-encoded.
///
/// These parameters define the encoding context for a set of source blocks.
/// To successfully decode, the receiver must possess the same `EpochParams`.
#[derive(Debug, Clone)]
pub struct EpochParams {
    /// Unique identifier for the epoch, typically used to distinguish
    /// between different files or data streams.
    pub epoch_id: u64,

    /// Number of source blocks in the epoch ($K$).
    /// This value determines the probability mass function of the
    /// Robust Soliton Distribution.
    pub k: u32,

    /// Root seed used to deterministically derive droplet-specific
    /// PRNGs. This ensures that the set of source block indices
    /// for `droplet_id` $N$ is stable across all peers.
    pub epoch_seed: [u8; 32],
}

impl EpochParams {
    /// Constructs a new [`EpochParams`] from the given identifiers and seed.
    ///
    /// # Examples
    ///
    /// ```
    /// use sef::droplet::EpochParams;
    ///
    /// let params = EpochParams::new(1, 256, [0xAB; 32]);
    /// assert_eq!(params.k, 256);
    /// ```
    pub fn new(epoch_id: u64, k: u32, epoch_seed: [u8; 32]) -> Self {
        Self {
            epoch_id,
            k,
            epoch_seed,
        }
    }

    /// Derives a deterministic per-droplet PRNG seed using SHA-256
    /// for domain separation and collision resistance.
    ///
    /// The resulting seed is unique to the (epoch, droplet) pair,
    /// ensuring that the Robust Soliton Distribution is sampled
    /// independently for every droplet.
    ///
    /// seed: SHA256(epoch_seed || b"droplet" || [epoch_id (LE)] || [droplet_id (LE)])
    fn droplet_rng(&self, droplet_id: u64) -> ChaCha8Rng {
        let hash = Sha256::new()
            .chain_update(self.epoch_seed)
            .chain_update(b"droplet")
            .chain_update(self.epoch_id.to_le_bytes())
            .chain_update(droplet_id.to_le_bytes())
            .finalize();

        ChaCha8Rng::from_seed(hash.into())
    }
}

/// An LT-code encoder that generates [`Droplet`]s from a fixed set of source blocks.
///
/// Borrows all inputs (zero-copy) and is parameterized over any
/// [`DegreeDistribution`], making it usable with [`RobustSoliton`](crate::distribution::RobustSoliton)
/// or custom distributions for testing.
pub struct Encoder<'e, D: DegreeDistribution> {
    /// Configuration and root seed for this encoding session.
    params: &'e EpochParams,

    /// The probability distribution used to sample the degree for each new droplet.
    dist: &'e D,

    /// The source data split into $K$ blocks.
    /// If blocks are non-uniform in length, they are implicitly
    /// zero-padded to the maximum block size during XOR operations.
    blocks: &'e [Vec<u8>],
}

impl<'e, D: DegreeDistribution> Encoder<'e, D> {
    /// Creates a new encoder over the given source blocks.
    ///
    /// # Panics
    ///
    /// Panics if `blocks.len() != params.k`.
    ///
    /// # Examples
    ///
    /// ```
    /// use sef::distribution::RobustSoliton;
    /// use sef::droplet::{EpochParams, Encoder};
    ///
    /// let k = 8;
    /// let blocks: Vec<Vec<u8>> = (0..k).map(|i| vec![i as u8; 32]).collect();
    /// let params = EpochParams::new(0, k as u32, [0u8; 32]);
    /// let rsd = RobustSoliton::new(k, 0.1, 0.5);
    /// let encoder = Encoder::new(&params, &rsd, &blocks);
    /// ```
    pub fn new(params: &'e EpochParams, dist: &'e D, blocks: &'e [Vec<u8>]) -> Self {
        assert_eq!(
            blocks.len(),
            params.k as usize,
            "blocks.len() ({}) != k ({})",
            blocks.len(),
            params.k
        );
        Self {
            params,
            dist,
            blocks,
        }
    }

    /// Generates a single [`Droplet`] for a specific `droplet_id`.
    ///
    /// This process follows the standard LT-code encoding pipeline:
    /// 1. Seed a PRNG with domain separation (epoch + droplet).
    /// 2. Sample a degree $d$ from the [`DegreeDistribution`].
    /// 3. Randomly select $d$ unique source block indices.
    /// 4. XOR the selected blocks together to form the droplet payload.
    ///
    /// The resulting [`Droplet`] is stateless and can be generated
    /// independently of any other droplets in the same epoch. The
    /// consumer is typically [`peeling_decode`](crate::decoder::peeling_decode).
    pub fn generate(&self, droplet_id: u64) -> Droplet {
        let k = self.params.k as usize;
        let mut rng = self.params.droplet_rng(droplet_id);

        // Sample degree from the distribution
        let degree = self.dist.sample_degree(&mut rng);

        // Sample `degree` unique indices in [0, k) using Floyd's algorithm via rand
        let mut indices: Vec<u32> = sample(&mut rng, k, degree)
            .into_iter()
            .map(|i| i as u32)
            .collect();
        indices.sort_unstable();

        // Gather the selected blocks and XOR them with adaptive padding
        let selected_blocks: Vec<&[u8]> = indices
            .iter()
            .map(|&i| self.blocks[i as usize].as_slice())
            .collect();

        let padded_len = selected_blocks.iter().map(|b| b.len()).max().unwrap_or(0);
        let payload = xor::xor_blocks(&selected_blocks);

        Droplet {
            epoch_id: self.params.epoch_id,
            droplet_id,
            indices,
            padded_len: padded_len as u32,
            payload,
        }
    }

    ///Generates a droplet into caller-supplied buffers, avoiding per-droplet allocation.
    ///
    /// `indices_buf` is cleared and filled with the sampled indices.
    /// `payload_buf` must be at least as long as the longest source block; it is
    /// zeroed and filled with the XOR result.
    ///
    /// Returns the degree (number of indices) and padded length so the caller
    /// can construct or serialize the droplet without further allocation.
    pub fn generate_into(
        &self,
        droplet_id: u64,
        indices_buf: &mut Vec<u32>,
        payload_buf: &mut [u8],
    ) -> (usize, u32) {
        let k = self.params.k as usize;
        let mut rng = self.params.droplet_rng(droplet_id);

        let degree = self.dist.sample_degree(&mut rng);

        indices_buf.clear();
        indices_buf.extend(sample(&mut rng, k, degree).into_iter().map(|i| i as u32));
        indices_buf.sort_unstable();

        let mut padded_len = 0;
        for &idx in indices_buf.iter() {
            padded_len = padded_len.max(self.blocks[idx as usize].len());
        }

        assert!(
            payload_buf.len() >= padded_len,
            "payload_buf.len() ({}) < padded_len ({})",
            payload_buf.len(),
            padded_len
        );

        let dst = &mut payload_buf[..padded_len];
        dst.fill(0);

        for &idx in indices_buf.iter() {
            let block = self.blocks[idx as usize].as_slice();
            let ok = xor::xor_into_fixed(dst, block);
            debug_assert!(ok);
        }

        (degree, padded_len as u32)
    }

    /// Convenience wrapper that generates `n` [`Droplet`]s with sequential IDs
    /// `0..n` via repeated calls to [`generate`](Encoder::generate).
    pub fn generate_n(&self, n: u64) -> Vec<Droplet> {
        (0..n).map(|id| self.generate(id)).collect()
    }
}

impl Droplet {
    /// Verifies the structural integrity of the droplet against the epoch's $K$ value.
    ///
    /// This ensures the droplet is decodable and won't cause panics during the
    /// peeling process. Specifically, it checks that:
    /// 1. The degree is at least 1.
    /// 2. The payload length matches the advertised `padded_len`.
    /// 3. All indices are within the valid range $[0, K)$.
    /// 4. Indices are strictly increasing (no duplicates, sorted).
    pub fn validate(&self, k: u32) -> Result<(), String> {
        if self.indices.is_empty() {
            return Err("droplet has no indices".into());
        }
        if self.payload.len() != self.padded_len as usize {
            return Err(format!(
                "payload length {} != padded_len {}",
                self.payload.len(),
                self.padded_len
            ));
        }
        // Indices must be sorted strictly increasing and in range [0, k)
        for (i, &idx) in self.indices.iter().enumerate() {
            if idx >= k {
                return Err(format!("index {} >= k={}", idx, k));
            }
            if i > 0 && idx <= self.indices[i - 1] {
                return Err(format!(
                    "indices not strictly sorted: [{}]={}, [{}]={}",
                    i - 1,
                    self.indices[i - 1],
                    i,
                    idx
                ));
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::distribution::RobustSoliton;

    fn test_blocks(k: usize) -> Vec<Vec<u8>> {
        // Create k synthetic blocks of varying sizes
        (0..k)
            .map(|i| {
                let size = 100 + (i % 50) * 10;
                let mut block = vec![0u8; size];
                // Fill with a recognizable pattern
                for (j, byte) in block.iter_mut().enumerate() {
                    *byte = ((i * 31 + j * 17) & 0xFF) as u8;
                }
                block
            })
            .collect()
    }

    #[test]
    fn test_generate_singleton() {
        let k = 50;
        let blocks = test_blocks(k);
        let seed = [42u8; 32];
        let params = EpochParams::new(0, k as u32, seed);

        // Use a distribution that always returns degree 1
        struct AlwaysOne;
        impl DegreeDistribution for AlwaysOne {
            fn sample_degree<R: rand::Rng + ?Sized>(&self, _rng: &mut R) -> usize {
                1
            }

            fn expected_degree(&self) -> f64 {
                1.0
            }
        }

        let encoder = Encoder::new(&params, &AlwaysOne, &blocks);
        let droplet = encoder.generate(0);

        assert_eq!(droplet.indices.len(), 1);

        // A singleton droplet's payload should equal the source block
        let idx = droplet.indices[0] as usize;
        assert_eq!(droplet.payload, blocks[idx]);
        assert!(droplet.validate(k as u32).is_ok());
    }

    #[test]
    fn test_generate_degree_2_xor() {
        let k = 50;
        let blocks = test_blocks(k);
        let seed = [42u8; 32];
        let params = EpochParams::new(0, k as u32, seed);

        // Distribution that always returns degree 2
        struct AlwaysTwo;
        impl DegreeDistribution for AlwaysTwo {
            fn sample_degree<R: rand::Rng + ?Sized>(&self, _rng: &mut R) -> usize {
                2
            }

            fn expected_degree(&self) -> f64 {
                2.0
            }
        }

        let encoder = Encoder::new(&params, &AlwaysTwo, &blocks);
        let droplet = encoder.generate(0);

        assert_eq!(droplet.indices.len(), 2);

        // Verify: XOR of the two selected blocks should equal the payload
        let idx0 = droplet.indices[0] as usize;
        let idx1 = droplet.indices[1] as usize;
        let expected = xor::xor_blocks(&[&blocks[idx0], &blocks[idx1]]);
        assert_eq!(droplet.payload, expected);
        assert!(droplet.validate(k as u32).is_ok());
    }

    #[test]
    fn test_deterministic_generation() {
        let k = 100;
        let blocks = test_blocks(k);
        let seed = [7u8; 32];
        let params = EpochParams::new(0, k as u32, seed);
        let dist = RobustSoliton::new(k, 0.1, 0.05);

        let encoder = Encoder::new(&params, &dist, &blocks);
        let d1 = encoder.generate(42);
        let d2 = encoder.generate(42);

        assert_eq!(d1.indices, d2.indices);
        assert_eq!(d1.payload, d2.payload);
        assert_eq!(d1.padded_len, d2.padded_len);
    }

    #[test]
    fn test_different_droplet_ids_differ() {
        let k = 100;
        let blocks = test_blocks(k);
        let seed = [7u8; 32];
        let params = EpochParams::new(0, k as u32, seed);
        let dist = RobustSoliton::new(k, 0.1, 0.05);

        let encoder = Encoder::new(&params, &dist, &blocks);
        let d1 = encoder.generate(0);
        let d2 = encoder.generate(1);

        // Extremely unlikely to have identical indices with different seeds
        assert_ne!(d1.indices, d2.indices);
    }

    #[test]
    fn test_generate_n() {
        let k = 50;
        let blocks = test_blocks(k);
        let seed = [0u8; 32];
        let params = EpochParams::new(0, k as u32, seed);
        let dist = RobustSoliton::new(k, 0.1, 0.5);

        let encoder = Encoder::new(&params, &dist, &blocks);
        let droplets = encoder.generate_n(200);

        assert_eq!(droplets.len(), 200);
        for (id, d) in droplets.iter().enumerate() {
            assert_eq!(d.droplet_id, id as u64);
            assert!(d.validate(k as u32).is_ok());
        }
    }

    #[test]
    fn test_validate_catches_bad_droplet() {
        let mut d = Droplet {
            epoch_id: 0,
            droplet_id: 0,
            indices: vec![5, 3], // not sorted
            padded_len: 10,
            payload: vec![0u8; 10],
        };
        assert!(d.validate(100).is_err());

        // Fix sorting but put index out of range
        d.indices = vec![3, 105];
        assert!(d.validate(100).is_err());

        // Fix sorting and index range
        d.indices = vec![3, 50];
        assert!(d.validate(100).is_ok());

        // Payload length mismatch
        d.padded_len = 20;
        assert!(d.validate(100).is_err());
    }

    #[test]
    fn test_singleton_recovers_original_block() {
        // Generate many droplets and verify that every singleton exactly matches its source
        let k = 30;
        let blocks = test_blocks(k);
        let seed = [99u8; 32];
        let params = EpochParams::new(0, k as u32, seed);
        let dist = RobustSoliton::new(k, 0.1, 0.5);

        let encoder = Encoder::new(&params, &dist, &blocks);
        let droplets = encoder.generate_n(500);

        for d in &droplets {
            if d.indices.len() == 1 {
                let idx = d.indices[0] as usize;
                // Payload should equal the source block
                // (it may be longer if padded, but the original block is at the start)
                assert_eq!(
                    &d.payload[..blocks[idx].len()],
                    &blocks[idx][..],
                    "singleton droplet {} doesn't match block {}",
                    d.droplet_id,
                    idx
                );
            }
        }
    }
}
